name: luxelane
description: Premium ride-hailing app — Luxelane
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  # State management & DI
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^7.7.0
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.2.7

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_messaging: ^15.0.4
  firebase_crashlytics: ^4.0.4
  firebase_performance: ^0.10.0
  cloud_functions: ^5.0.4

  # Payments
  flutter_stripe: ^10.2.0

  # Maps
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  geolocator: ^13.0.1
  map_launcher: ^3.1.0
  url_launcher: ^6.3.0

  # HTTP
  http: ^1.2.2

  # Utilities
  dartz: ^0.10.1
  rxdart: ^0.27.7
  intl: ^0.19.0
  uuid: ^4.4.2
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0

  # Storage
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  # fonts are loaded via Google Fonts fallback on web
